### ISSUE TITLE
Demo is still broken

### ISSUE THREAD

**Issue by sclearion** [Polymer/paper-shadow#28]
Using the updated tags/ master source as suggested in earlier issue fixes, the demo still does not render the shadow when the paper-shadow tag is inside a div like the example shows.

Any suggestions?

**Comment by morethanreal** [comment]
The `master` branch isn't guaranteed to be working since it's under active development. The current release appears to be working: https://www.polymer-project.org/components/paper-shadow/demo.html

Please wait for the next release for changes not in the current release.
